{% set name = "gcab" %}
{% set version = "1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.acc.umu.se/pub/GNOME/sources/gcab/{{ version }}/gcab-{{ version }}.tar.xz
  sha256: 2f0c9615577c4126909e251f9de0626c3ee7a152376c15b5544df10fc87e560b
  patches:
    - 0001-Explicitly-specify-gir-dir.patch

build:
  number: 0
  # Not supported on win
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("gcab") }}

requirements:
  build:
    - {{ compiler('c') }}
    - ninja
    - meson
    - pkg-config
    - vala
    - glib  # [build_platform != target_platform]
  host:
    - gobject-introspection
    - gettext
    - glib
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libgcab-1.0${SHLIB_EXT}
    - gcab --version

about:
  home: https://github.com/GNOME/gcab
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file:
    - COPYING
  summary: A GObject library to create cabinet files
  dev_url: https://github.com/GNOME/gcab

extra:
  recipe-maintainers:
    - isuruf
    - xhochy
