{% set name = "gcab" %}
{% set version = "1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.acc.umu.se/pub/GNOME/sources/gcab/{{ version }}/gcab-{{ version }}.tar.xz
  sha256: 46bf7442491faa4148242b9ec2a0786a5f6e9effb1b0566e5290e8cc86f00f0c
  patches:
    - disable-linker-script.patch  # [osx]

build:
  number: 0
  # Not supported on win
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("gcab") }}

requirements:
  build:
    - {{ compiler('c') }}
    - ninja
    - meson
    - pkg-config
    - glib  # [build_platform != target_platform]
  host:
    - gobject-introspection
    - glib
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libgcab-1.0${SHLIB_EXT}
    - gcab --version

about:
  home: https://github.com/GNOME/gcab
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file:
    - COPYING
  summary: A GObject library to create cabinet files
  dev_url: https://github.com/GNOME/gcab

extra:
  recipe-maintainers:
    - isuruf
    - xhochy
